### ISSUE TITLE
[CMake] Wrong paths for cmake files and pkgbuild

### ISSUE THREAD

**Issue by julianxhokaxhiu** [sithlord48/ff7tk#113]
**Describe the bug**
I've created a simple `vcpkg` portfile that allows to build this library and make use of it in Makou Reactor. Thw whole library builds just fine but I found out two misplaced elements that just need to be put differently once you build the library using `CMake`.

- ~`lib/cmake/ff7tk/*.cmake` should be instead put in `share/*.cmake`~ NO ACTION REQUIRED.
- `share/pkgconfig/ff7tk.pc` should be instead put in `lib/pkgconfig/ff7tk.pc`

Thanks again and feel free to ping me if any other question arises!

**To Reproduce**
1. Build the project using CMake
2. Look at the exported artifacts

**Expected behavior**
The cmake files and the pkgconfig files are put in the right folders.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Compiler: MSVC
 - Version: [v0.83.0](https://github.com/sithlord48/ff7tk/releases/tag/v0.83.0)
 - Qt Version used: QT 6.4.2

**Additional context**
N/A

**Comment by sithlord48** [comment]
Update Notes : Cmake path is ok ; pkgbuild path is not
